### ISSUE TITLE
Unsupported model: F@ST F5359 / KPN Box 12

### ISSUE THREAD

**Issue by geert36** [iMicknl/ha-sagemcom-fast#19]
I recently got the Sagemcom box F@ST F5359. It is the new modem distributed by KPN known as the Box 12.

I tried to get some more information with executing `$.xmo.getValuesTree("Device/DeviceInfo");` in the web console, this results in nothing.

Is it possible to support this device? Please let me know if you need more information.
I want to use it for presence detection in Home Assistant.

## Model information

| Key                      | Value |
| ------------------------ | ----- |
| Model name               | F@ST F5359 |
| Hardware Version         | 1.0 |
| Software Version         | SGEJ10000310 |

**Comment by iMicknl** [comment]
@geert36 I just published a new version (same URL as before). In your case, you should be able to select 'Uses an SSL certificate':

Please let me know if it works or if you have any errors in the log.

<img width="613" alt="Screen Shot 2021-05-02 at 22 44 16" src="https://user-images.githubusercontent.com/1424596/116827166-f98b4f00-ab97-11eb-9d1e-7be6adc93bca.png">

**Comment by geert36** [comment]
I deleted the integration and uploaded the new files. When adding the new integration, I get the following screen: ![2021_05_03_12_18_46_Window](https://user-images.githubusercontent.com/77209691/116866002-f4b3b300-ac0a-11eb-8ea2-a41241a26420.png)

So the integration is added and no more errors in the log file. Unfortunately no device is created or displayed in the device tab.
![2021_05_03_12_32_26_Window](https://user-images.githubusercontent.com/77209691/116866444-b23ea600-ac0b-11eb-9075-2a17cf958821.png)

**Comment by iMicknl** [comment]
I think you face the `MaximumSessionCount` again, but I accidentally changed the logging to something that is not supported in the current (non-dev) Home Assistant version yet... I added back the logging.

I wonder if this session will be killed after some time, thus that it could work after a day or so...

**Comment by geert36** [comment]
Correct, the error is back in the logging: 
![2021-05-03 17_51_44-Instellingen - Home Assistant](https://user-images.githubusercontent.com/77209691/116899793-4b83b180-ac38-11eb-951e-ad4933e00cb3.png)

I will wait for 24 hours and let you know if it starts working. 
This is a well-known error for me, I saw this error regardly in the web UI of the KPN box.

**Comment by geert36** [comment]
Short after taking the screenshot of previous post, fetching of data succeeded: 
`2021-05-03 16:13:29 DEBUG (MainThread) [custom_components.sagemcom_fast] Finished fetching sagemcom_hosts data in 0.570 seconds`
`2021-05-03 19:43:18 ERROR (MainThread) [custom_components.sagemcom_fast] Error fetching sagemcom_hosts data: Error communicating with API: list index out of range`
`2021-05-03 19:43:18 DEBUG (MainThread) [custom_components.sagemcom_fast] Finished fetching sagemcom_hosts data in 0.354 seconds`

**Comment by iMicknl** [comment]
But does it work? :-). Did it create devices / entities?

**Comment by geert36** [comment]
Hmm no, unfortunately not. Still no devices /entities :( How can I help you to solve this?

**Comment by copini** [comment]
The main issue with this device (besides the SSL requirement) is that querying `Device/DeviceInfo` yields an `XMO_UNKNOWN_PATH_ERR` error instead of device info. This custom component currently relies on that query (through `client.get_device_info()`) to work.

Querying individual values does work (as does `client.get_hosts()`), so it is possible to work around the problem by changing a few things in `async_setup_entry`. Instead of relying on `client.get_device_info()` you could use `client.get_value_by_xpath()` to get the individual values required to register the device in Home Assistant. The only thing I couldn't get is the device manufacturer, but I guess that could be hardcoded. The rest works:
```
Device/DeviceInfo/MACAddress: 84:1E:A3:xx:xx:xx
Device/DeviceInfo/SerialNumber: xxxxx
Device/DeviceInfo/ModelNumber: sagemcom_fast5359__kpn
Device/DeviceInfo/ModelName: F5359
Device/DeviceInfo/SoftwareVersion: SGEJ10000310
```
I'm just not sure if this would work for all other devices supported by this integration as well. Otherwise maybe this could be a toggle in the setup just like SSL support, what do you think?

I'm also wondering if there are more new Sagemcom F@st devices with this issue, and if perhaps it should be addressed in [python-sagemcom-api](https://github.com/iMicknl/python-sagemcom-api) instead?

**Comment by copini** [comment]
Another issue is related to the `XMO_MAX_SESSION_COUNT_ERR` error mentioned earlier. This device indeed seems to allow only one active session per user, and it has only one fixed (admin) user. There's no option to create extra accounts.

As this integration does not log out from the admin session, it can effectively lock you out from using the modem web interface because it's scanning every 10 seconds (by default).

It would be great if the logout API command (`{"method": "logOut"}`) could be added to [python-sagemcom-api](https://github.com/iMicknl/python-sagemcom-api) and this integration would log out after every scan. That way we can still log in to the web interface most of the time. The integration would not work while being logged in though, so it's best to manually log out when you're done instead of closing the browser tab (otherwise the integration can't scan for another 5 minutes).

**Comment by copini** [comment]
I created a very simplistic pull request that fixes the main issue. This does not solve the MaximumSessionCount issue, but it does make the device work in Home Assistant.

I got the MaximumSessionCount error on the first setup attempt, but devices started to show up a few minutes later. You can try it out in [my fork](https://github.com/copini/ha-sagemcom-fast) (merged it to `master` there so it's easy to get up and running in HACS). I recommend setting the scan interval to at least 5 minutes until the MaximumSessionCount/logout problem is fixed so you're not locked out of the device's web interface.

**Comment by rhpijnacker** [comment]
Any progress on this?
I just stumbled upon this and would love to connect my HA to my KPN Box v12.
If needed I would be happy to hack away on some code to get this to work.

**Comment by iMicknl** [comment]
@rhpijnacker unfortunately I haven't had much time lately to work on this integration. I would be happy to release a new version, if someone has time to help out a bit.

**Comment by rhpijnacker** [comment]
@iMicknl I send some PRs.
To make this work we will need to logout after every login/query.
With these change's I'm seeing devices and entities getting created, which is how far the current integration goes, right?
What would be the next step to get event notification on device changes?

**Comment by davidrustingha** [comment]
Hi guys, happy new year first of all!

I'd be happy to test the integration for the KPN box 12. I have it at home, and have tried to get it working by checking the pending pull requests, but I havent got it working yet.
Let me know if I can be of any help!

**Comment by rhpijnacker** [comment]
@davidrustingha Happy new year to you too.
What is going wrong? For me it works, so I'm curious to why it does not work for you.

**Comment by davidrustingha** [comment]
@rhpijnacker well I tried installing the current version on this repo, that gives me the 'Failed to connect, please try again' error. 

I've installed the update mentioned here, it loads properly, but then I get the 'Maximum session count reached' error. It does not create entities also. 
> @geert36 could you give https://github.com/iMicknl/ha-sagemcom-fast/archive/refs/heads/feature/add_ssl_support.zip a try? Extract this file and place `custom_components/sagemcom_fast` in your `custom_components` folder. (overwrite the previous one).
When I rebooted after adding a debug log output I got this error:

```
2022-01-02 15:12:58 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry mijnmodem.kpn for sagemcom_fast
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/sagemcom_fast/__init__.py", line 122, in async_setup_entry
gateway = await client.get_device_info()
File "/usr/local/lib/python3.9/site-packages/sagemcom_api/client.py", line 337, in get_device_info
data = await self.get_value_by_xpath("Device/DeviceInfo")
File "/usr/local/lib/python3.9/site-packages/sagemcom_api/client.py", line 307, in get_value_by_xpath
response = await self.__api_request_async([actions], False)
File "/usr/local/lib/python3.9/site-packages/sagemcom_api/client.py", line 241, in __api_request_async
raise UnknownPathException(action_error)
sagemcom_api.exceptions.UnknownPathException: {'code': 16777242, 'description': 'XMO_UNKNOWN_PATH_ERR'}
```
After a disable/enable and reboot I get the session count error again.

What can I do from here?

**Comment by davidrustingha** [comment]
I have also tried to setup @copini's version, but when I fill out my information during setup it exits with the session count error before it sets up

**Comment by rhpijnacker** [comment]
So, what you'll need is:
* [Add SSL support #18](https://github.com/iMicknl/ha-sagemcom-fast/pull/18)
* [Log out of Sagemcom client after every query #30](https://github.com/iMicknl/ha-sagemcom-fast/pull/30)
but also
* [Add logout API method #107](https://github.com/iMicknl/python-sagemcom-api/pull/107)
* [Implement get_device_info for F5359 used by KPN Box 12 #108](https://github.com/iMicknl/python-sagemcom-api/pull/108)
both of which are merged into master by @iMicknl. However, this is not yet released into PyPI, so still needs to be set up locally.

If you want, you could use the [merge](https://github.com/rhpijnacker/ha-sagemcom-fast/tree/merge) branch. This contains both PRs.

For the KPN Box v12 you will need to select SHA512 and check the "Uses a SSL-certificate" option.

**Comment by davidrustingha** [comment]
As I understood it the merge branch had all the PR's, right? After adding that it gives me this error

This error originated from a custom integration.

```
Logger: custom_components.sagemcom_fast.config_flow
Source: custom_components/sagemcom_fast/config_flow.py:70
Integration: sagemcom_fast (documentation, issues)
First occurred: 18:05:24 (1 occurrences)
Last logged: 18:05:24

'SagemcomClient' object has no attribute 'logout'
Traceback (most recent call last):
  File "/config/custom_components/sagemcom_fast/config_flow.py", line 86, in async_step_user
    return await self.async_validate_input(user_input)
  File "/config/custom_components/sagemcom_fast/config_flow.py", line 70, in async_validate_input
    await client.logout()
AttributeError: 'SagemcomClient' object has no attribute 'logout'

```

**Comment by rhpijnacker** [comment]
Looks like you're missing [https://github.com/iMicknl/python-sagemcom-api/pull/107](https://github.com/iMicknl/python-sagemcom-api/pull/107). Are you sure you are using the latest sagemcom-api library from git? (Not the one from PyPI.)

**Comment by davidrustingha** [comment]
I checked and I have version 1.0.5 installed, that should be the most recent version according to the github repo https://github.com/iMicknl/python-sagemcom-api

**Comment by rhpijnacker** [comment]
Version 1.0.5 indeed does not contain the `logout` function. 
If you take the latest from master, it should, as [this commit](https://github.com/iMicknl/python-sagemcom-api/commit/bcb44e0afbec1459c6c3833b120ddb3bc617e6af) added that function.

If you still get the error that "object has no attribute 'logout'", then it isn't picking up the updated version of client.py.

**Comment by davidrustingha** [comment]
Im pretty sure I have. Installed it with `pip install git+https://github.com/iMicknl/python-sagemcom-api`

It either gives me the session count error or the logout error. I can't get past the initial set up.

**Comment by iMicknl** [comment]
@rhpijnacker 1.06 is published. However, you should be able to link to a specific branch as well in the manifest.json. See https://developers.home-assistant.io/docs/creating_integration_manifest/ for the correct notation.

**Comment by rhpijnacker** [comment]
Oh cool. I'm new to all this (Home Assistant, python, pip, etc.) so good to know how to handle dependencies.
Thanks.

**Comment by geert36** [comment]
Thanks for the latest update @iMicknl !
I removed everything and did a clean install. Now I've got this error:
![image](https://user-images.githubusercontent.com/77209691/151703231-a385e977-88b5-4e96-85d1-e0af5f4b969b.png)
![image](https://user-images.githubusercontent.com/77209691/151703263-d693c539-a624-40eb-8346-faa0cb0c0712.png)

**Comment by iMicknl** [comment]
Are you sure that is the right URL and port? It seems it can not connect.

@rhpijnacker could perhaps help. I updated the underlying API a bit, so that new changes can be merged faster :-). Apologies for the delays.

**Comment by geert36** [comment]
Yes still using the same URL and port. When using [the merge](https://github.com/rhpijnacker/ha-sagemcom-fast/tree/merge) of @rhpijnacker and changing sagemcom api to 1.0.6, it is still working.

**Comment by rhpijnacker** [comment]
@geert36 Looks like @iMicknl did not yet merge [my changes](https://github.com/iMicknl/ha-sagemcom-fast/pull/30), or the  [SSL support changes](https://github.com/iMicknl/ha-sagemcom-fast/pull/18).
So, basically, master is not yet ready for using on a KPN Box 12.

**Comment by iMicknl** [comment]
@rhpijnacker I will probably remove the log out after every request as the default option, but move it to the options flow. I believe it worked in your case, but you weren't able to open the normal router interface at the same time?

It is way more resource friendly to keep the session open, and in my case, the current logout() way does even break the integration. Apparently my model doesn't like to login/logout that frequent.

**Comment by rhpijnacker** [comment]
@iMicknl If it causes problems for other integrations, then it makes a lot of sense to make this optional.
You are correct that the KPN Box v12 devices allow only one active login session at any time.

If you want me to test out your changes, then feel free to let me know.

**Comment by julianborghuis** [comment]
hey mick,

do you know if you want to login at the ip you can use http://192.168.2.254/2.0/gui/#/login/ instead of mijnmodem.kpn. this will bypass the redirection to mijnmodem.kpn. 
Is there any progress on this model???
